apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hummingbot.fullname" . }}
  labels:
  {{- include "hummingbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "hummingbot.fullname" . }}
  selector:
    matchLabels:
  {{- include "hummingbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "hummingbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hummingbot.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          stdin: true
          {{- if .Values.ttyd.enabled -}}
          command: [/bin/bash]
          args:
            - -c
            - ttyd /home/hummingbot/miniconda3/envs/$(head -1 setup/environment-linux.yml | cut -d' ' -f2)/bin/python3 bin/hummingbot_quickstart.py --auto-set-permissions $(id -nu):$(id -ng)
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "hummingbot.fullname" . }}-config
              subPath: data
            - mountPath: /conf
              name: {{ include "hummingbot.fullname" . }}-config
              subPath: conf
            - mountPath: /scripts
              name: {{ include "hummingbot.fullname" . }}-config
              subPath: scripts
            - mountPath: /logs
              name: {{ include "hummingbot.fullname" . }}-logs
          {{- if .Values.ttyd.enabled -}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "hummingbot.fullname" . }}-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.config.size | default "4Gi" }}
    - metadata:
        name: {{ include "hummingbot.fullname" . }}-logs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.logs.size | default "4Gi" }}
